name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --frozen

      - name: Ruff check
        run: uv run ruff check src/ tests/

      - name: Ruff format
        run: uv run ruff format --check src/ tests/

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run unit tests
        run: uv run pytest --tb=short -v
